# Generated by Django 2.1.7 on 2019-03-03 11:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
import emps.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=datetime.date.today)),
                ('working_hours', emps.models.MinMaxHours()),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('SICKLEAVE', 'Sick Leave'), ('DAYOFF', 'Day OFF')], default='Present', max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('mobil', phonenumber_field.modelfields.PhoneNumberField(max_length=128, unique=True)),
                ('hireDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emps.Employee'),
        ),
    ]
