# Generated by Django 2.1.7 on 2019-03-04 11:11

from django.db import migrations, models
import emps.models


class Migration(migrations.Migration):

    dependencies = [
        ('emps', '0004_auto_20190303_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='working_hours',
            field=emps.models.MinMaxHours(default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hireDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
