# Generated by Django 2.1.7 on 2019-03-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emps', '0005_auto_20190304_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
